apiVersion: v1
data:
  values.yaml: |
    appInit:
      resources:
        limits:
          cpu: 99
          memory: 768Mi
        requests:
          cpu: 0.1
          memory: 256Mi
    backgroundReplicaCount: 1
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      enabled: true
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seLinuxOptions: null
      seccompProfile:
        type: RuntimeDefault
    dbInit:
      image:
        imagePullPolicy: IfNotPresent
        registry: registry-1.docker.io
        repository: library/postgres
        tag: 16.9-alpine3.20@sha256:e5507c984377515b8c9922b0eb19f55aba2063fdc7bccf268cefd53133f97054
      resources:
        limits:
          cpu: 99
          memory: 768Mi
        requests:
          cpu: 0.1
          memory: 256Mi
    environment:
      OPENPROJECT_APP__TITLE: Projekte - openDesk
      OPENPROJECT_AUTHENTICATION_GLOBAL__BASIC__AUTH_PASSWORD: f97b99dba2add5cb8c97c5a33d3cf97dbd6e9dd5
      OPENPROJECT_AUTHENTICATION_GLOBAL__BASIC__AUTH_USER: 8ff774f3221344ed216c54510e38256d4b1f2e7f
      OPENPROJECT_DEFAULT__COMMENT__SORT__ORDER: desc
      OPENPROJECT_EMAIL__DELIVERY__METHOD: smtp
      OPENPROJECT_HOME__URL: https://portal.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com/
      OPENPROJECT_LOG__LEVEL: info
      OPENPROJECT_LOGIN__REQUIRED: "true"
      OPENPROJECT_MAIL__FROM: no-reply@opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      OPENPROJECT_OAUTH__ALLOW__REMAPPING__OF__EXISTING__USERS: "true"
      OPENPROJECT_OMNIAUTH__DIRECT__LOGIN__PROVIDER: keycloak
      OPENPROJECT_OPENID__CONNECT_KEYCLOAK_ISSUER: https://id.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com/realms/opendesk
      OPENPROJECT_OPENID__CONNECT_KEYCLOAK_POST__LOGOUT__REDIRECT__URI: https://projects.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com/
      OPENPROJECT_SEED_DESIGN_ACCENT__COLOR: '#571EFA'
      OPENPROJECT_SEED_DESIGN_FAVICON: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTExIiBoZWlnaHQ9IjExMSIgdmlld0JveD0iMCAwIDExMSAxMTEiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHg9IjAuNSIgeT0iMC41IiB3aWR0aD0iMTEwIiBoZWlnaHQ9IjExMCIgcng9IjIwIiBmaWxsPSJ3aGl0ZSIvPgo8cGF0aCBkPSJNMjQuMzI5NiA4Ni43MDY5TDI0LjMyOTYgMjQuMzc3MkgxNi41MzQzTDE2LjUzNDMgODYuNzA2OUgyNC4zMjk2WiIgZmlsbD0iIzU3MUVGQSIvPgo8cGF0aCBkPSJNODYuODM1MyA1OS40Mzk3SDU1LjY3NTlDNTEuMzcwNyA1OS40Mzk3IDQ3Ljg4MDYgNjIuOTI5OCA0Ny44ODA2IDY3LjIzNVY3NS4wMTk0QzQ3Ljg4MDYgNzkuMzI0NiA1MS4zNzA3IDgyLjgxNDcgNTUuNjc1OSA4Mi44MTQ3SDg2LjgzNTNDOTEuMTQwNSA4Mi44MTQ3IDk0LjYzMDYgNzkuMzI0NiA5NC42MzA2IDc1LjAxOTRWNjcuMjM1Qzk0LjYzMDYgNjIuOTI5OCA5MS4xNDA1IDU5LjQzOTcgODYuODM1MyA1OS40Mzk3WiIgZmlsbD0iIzU3MUVGQSIvPgo8cGF0aCBkPSJNNjMuNDYwMyAyOC4yODAzSDM5LjkyMDNDMzUuNjE1MSAyOC4yODAzIDMyLjEyNSAzMS43NzA0IDMyLjEyNSAzNi4wNzU2VjQzLjg1OTlDMzIuMTI1IDQ4LjE2NTIgMzUuNjE1MSA1MS42NTUzIDM5LjkyMDMgNTEuNjU1M0g2My40NjAzQzY3Ljc2NTUgNTEuNjU1MyA3MS4yNTU2IDQ4LjE2NTIgNzEuMjU1NiA0My44NTk5VjM2LjA3NTZDNzEuMjU1NiAzMS43NzA0IDY3Ljc2NTUgMjguMjgwMyA2My40NjAzIDI4LjI4MDNaIiBmaWxsPSIjMzQxMjkxIi8+Cjwvc3ZnPgo=
      OPENPROJECT_SEED_DESIGN_HEADER__BG__COLOR: '#ffffff'
      OPENPROJECT_SEED_DESIGN_HEADER__ITEM__BG__HOVER__COLOR: '#f5f5f5'
      OPENPROJECT_SEED_DESIGN_LOGO: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODIiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCA4MiAxNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTQuNDM1MzggMy45MDQ3OUM3LjEzMDM2IDMuOTA0NzkgOC44NTI2IDUuODgxNjIgOC44NTI2IDguMzAyOEM4Ljg1MjYgMTAuNzI0IDcuMTMwMzYgMTIuNzAwOCA0LjQzNTM4IDEyLjcwMDhDMS43NDA0IDEyLjcwMDggMCAxMC43MjQgMCA4LjMwMjhDMCA1Ljg4MTYyIDEuNzIyMjUgMy45MDQ3OSA0LjQzNTM4IDMuOTA0NzlaTTQuNDM1MzggMTEuNjI3MkM2LjQ5ODgxIDExLjYyNzIgNy41OTEzMiAxMC4wOTI4IDcuNTkxMzIgOC4zMDI4QzcuNTkxMzIgNi41MTI3NiA2LjQ5ODgxIDQuOTc4NDQgNC40MzUzOCA0Ljk3ODQ0QzIuMzcxOTUgNC45Nzg0NCAxLjI2MzEgNi41MTI3NiAxLjI2MzEgOC4zMDI4QzEuMjYzMSAxMC4wOTI4IDIuMzUzOCAxMS42MjcyIDQuNDM1MzggMTEuNjI3MloiIGZpbGw9ImJsYWNrIi8+CjxwYXRoIGQ9Ik0xMC40OTIyIDQuMDc1MjZIMTEuNzU1M1Y2LjIyMjU4QzEyLjM1MjQgNC44MDc5NiAxMy42MTU1IDMuOTA0NzkgMTUuNDU3NSAzLjkwNDc5QzE3LjgyOTQgMy45MDQ3OSAxOS40MzE5IDUuNjk0ODIgMTkuNDMxOSA4LjMxOTEyQzE5LjQzMTkgMTAuOTQzNCAxNy44Mjk0IDEyLjcwMDggMTUuNDU3NSAxMi43MDA4QzEzLjU4MSAxMi43MDA4IDEyLjMzNiAxMS43NjMyIDExLjc1NTMgMTAuMzgzVjE1LjYzMzRIMTAuNDkyMlY0LjA3NTI2Wk0xNS4wNjM3IDExLjYyNzJDMTYuNzY5NiAxMS42MjcyIDE4LjE2ODggMTAuNTY5OCAxOC4xNjg4IDguMzE5MTJDMTguMTY4OCA2LjA2ODQzIDE2Ljc2OTYgNC45Nzg0NCAxNS4wNjM3IDQuOTc4NDRDMTMuMzU3OCA0Ljk3ODQ0IDExLjgwNjEgNi4wODY1NiAxMS44MDYxIDguMzE5MTJDMTEuODA2MSAxMC41NTE3IDEzLjM3NTkgMTEuNjI3MiAxNS4wNjM3IDExLjYyNzJaIiBmaWxsPSJibGFjayIvPgo8cGF0aCBkPSJNMjQuNzg3MSAzLjkwNDY1QzI3LjIwOTggMy45MDQ2NSAyOC44MzA0IDUuNDIyNjQgMjguODMwNCA4LjAxMjQ4VjguNTIzOTJIMjIuMDI0OUMyMi4wNzU3IDEwLjI5NzYgMjIuOTc5NSAxMS42NTk3IDI0Ljg1NiAxMS42NTk3QzI2LjQwNzcgMTEuNjU5NyAyNy4zMTMzIDEwLjg0MTcgMjcuNjIgOS41Nzk0NUgyOC44NjQ5QzI4LjUwNzQgMTEuMDc5MyAyNy40ODM4IDEyLjY5ODkgMjQuODkwNSAxMi42OTg5QzIyLjE0NDcgMTIuNjk4OSAyMC44MTQ1IDEwLjY1MzEgMjAuODE0NSA4LjE4MTE1QzIwLjgxNDUgNS40NTM0NyAyMi40MDA2IDMuOTAyODMgMjQuNzg4OSAzLjkwMjgzTDI0Ljc4NzEgMy45MDQ2NVpNMjcuNTgzNyA3LjUzNTVDMjcuNDYzOSA1Ljg4MTQ4IDI2LjM1NSA0Ljk0Mzg1IDI0Ljc2ODkgNC45NDM4NUMyMy4yODQ0IDQuOTQzODUgMjIuMTc1NiA1Ljg5NzgxIDIyLjAzOTQgNy41MzU1SDI3LjU4MzdaIiBmaWxsPSJibGFjayIvPgo8cGF0aCBkPSJNMzAuNjAzNSA0LjA3NTI2SDMxLjg2NjZWNi40Mjc1MkMzMi4zMjc2IDQuODU4NzUgMzMuNTIxNyAzLjkwNDc5IDM1LjM4MDEgMy45MDQ3OUMzNy4yMzg0IDMuOTA0NzkgMzguNDE2MiA1LjEzMjYgMzguNDE2MiA3LjM0ODg0VjEyLjUzMDNIMzcuMTM2OFY3LjQ1MDRDMzcuMTM2OCA1LjY5NDgyIDM2LjQ1NDQgNC45Nzg0NCAzNC45NTM2IDQuOTc4NDRDMzMuMDQyNiA0Ljk3ODQ0IDMxLjg2NjYgNi41ODE2OCAzMS44NjY2IDguODQ4N1YxMi41MzAzSDMwLjYwMzVWNC4wNzUyNloiIGZpbGw9ImJsYWNrIi8+CjxwYXRoIGQ9Ik00MC41NDg4IDAuNTExMjNINDQuOTY3OUM0Ni4yMTgzIDAuNTExMjMgNDcuMzIxNyAwLjY2NTM4NiA0OC4yNzgxIDAuOTcxODg3QzQ5LjIzMjcgMS4yNzgzOSA1MC4wMTQ4IDEuODc1MDcgNTAuNjIyOCAyLjc2MTkyQzUxLjIzMDggMy42NDg3OCA1MS41MzU2IDQuODk4MzYgNTEuNTM1NiA2LjUxMjQ4QzUxLjUzNTYgOC4xMjY2IDUxLjIzMDggOS4zOTQzMSA1MC42MjI4IDEwLjI3OTRDNTAuMDE0OCAxMS4xNjYyIDQ5LjIzMjcgMTEuNzYyOSA0OC4yNzgxIDEyLjA2OTRDNDcuMzIxNyAxMi4zNzU5IDQ2LjIyMDEgMTIuNTMwMSA0NC45Njc5IDEyLjUzMDFINDAuNTQ4OFYwLjUxMTIzWk00NC45Njc5IDEwLjEyN0M0NS44MzE3IDEwLjEyNyA0Ni41MjMyIDEwLjA1ODEgNDcuMDQwNCA5LjkyMjA3QzQ3LjU1NzYgOS43ODYwNSA0Ny45Nzg2IDkuNDU5NiA0OC4zMDM1IDguOTQwOTFDNDguNjI4MyA4LjQyNDAzIDQ4Ljc4OTggNy42MTMzNCA0OC43ODk4IDYuNTEyNDhDNDguNzg5OCA1LjQxMTYyIDQ4LjYyNDcgNC42MTU0NCA0OC4yOTYyIDQuMDkxM0M0Ny45NjU5IDMuNTY4OTggNDcuNTQ0OSAzLjIzODkxIDQ3LjAzMzEgMy4xMDI4OEM0Ni41MjEzIDIuOTY2ODYgNDUuODMzNSAyLjg5Nzk1IDQ0Ljk2OTcgMi44OTc5NUg0My4yODAxVjEwLjEyN0g0NC45Njk3SDQ0Ljk2NzlaIiBmaWxsPSJibGFjayIvPgo8cGF0aCBkPSJNNTMuMzE1OCA1LjgyMjA1QzUzLjY5NjkgNS4xNTY0NiA1NC4yMjUgNC42NDg2NSA1NC45MDE5IDQuMjk2OEM1NS41Nzg5IDMuOTQ0OTYgNTYuMzU1NiAzLjc2OTA0IDU3LjIzMDMgMy43NjkwNEM1OC42NjQgMy43NjkwNCA1OS43ODM4IDQuMTQ5OSA2MC41OTEzIDQuOTExNjJDNjEuMzk4OSA1LjY3MzM0IDYxLjgwMTggNi43MjUyMyA2MS44MDE4IDguMDY1NDlWOC43ODE4N0g1NS4zNTM4QzU1LjM5OTIgOS4zOTQ4NyA1NS41OTM0IDkuODc1NDggNTUuOTM0NiAxMC4yMjE5QzU2LjI3NTcgMTAuNTY4MyA1Ni43NDIyIDEwLjc0MjQgNTcuMzMzOCAxMC43NDI0QzU3Ljg0NTUgMTAuNzQyNCA1OC4yNjg0IDEwLjYzNTQgNTguNjA0MSAxMC40MTc4QzU4LjkzOTkgMTAuMjAxOSA1OS4xNTIyIDkuODk1NDMgNTkuMjQ0OCA5LjQ5NjQ0SDYxLjgyQzYxLjY4MzkgMTAuNDUwNCA2MS4yMjQ3IDExLjIyNDggNjAuNDQ2MiAxMS44MTQyQzU5LjY2NzYgMTIuNDA1NSA1OC42MzUgMTIuNzAxMSA1Ny4zNTAxIDEyLjcwMTFDNTYuNDA2NCAxMi43MDExIDU1LjU4NzkgMTIuNTEwNyA1NC44OTI5IDEyLjEyOThDNTQuMTk5NiAxMS43NDg5IDUzLjY2NzkgMTEuMjE3NiA1My4yOTc3IDEwLjUzNTZDNTIuOTI3NCA5Ljg1MzcyIDUyLjc0NDEgOS4wNzAyNCA1Mi43NDQxIDguMTgzMzhDNTIuNzQ0MSA3LjI5NjUyIDUyLjkzNDcgNi40ODc2NSA1My4zMTU4IDUuODIyMDVaTTU5LjI3NzQgNy4zODE3NkM1OS4yMzIxIDYuODM1ODYgNTkuMDMwNiA2LjQxNTExIDU4LjY3MTMgNi4xMTk0OUM1OC4zMTM4IDUuODIzODcgNTcuODQ5MiA1LjY3Njk2IDU3LjI4MTEgNS42NzY5NkM1Ni43MTMxIDUuNjc2OTYgNTYuMjcyMSA1LjgyNTY4IDU1LjkyNTUgNi4xMTk0OUM1NS41Nzg5IDYuNDE1MTEgNTUuMzgyOSA2LjgzNTg2IDU1LjMzNzUgNy4zODE3Nkg1OS4yNzc0WiIgZmlsbD0iYmxhY2siLz4KPHBhdGggZD0iTTY0LjEwNzUgMTEuODY0N0M2My4zNTYxIDExLjMwOCA2Mi45ODA1IDEwLjQ5IDYyLjk4MDUgOS40MDkxSDY1LjU3MzhDNjUuNTczOCA5Ljg5ODc4IDY1LjcyODEgMTAuMjU5NyA2Ni4wMzQ4IDEwLjQ5MThDNjYuMzQxNSAxMC43MjU4IDY2LjgxMzMgMTAuODQxOSA2Ny40NTAzIDEwLjg0MTlDNjcuOTE2NyAxMC44NDE5IDY4LjI1NDMgMTAuNzgyIDY4LjQ2NDggMTAuNjYyM0M2OC42NzUzIDEwLjU0MjYgNjguNzgwNiAxMC4zNTIyIDY4Ljc4MDYgMTAuMDkxQzY4Ljc4MDYgOS45MDk2NiA2OC43MTg5IDkuNzYwOTQgNjguNTkzNyA5LjY0ODVDNjguNDY4NCA5LjUzNDI0IDY4LjI2ODggOS40MzgxMiA2Ny45OTY2IDkuMzU4MzJMNjUuMzY4OCA4LjY0MTk0QzY0Ljc4OCA4LjQ5NTA0IDY0LjI4ODkgOC4yMzAyNSA2My44Njc5IDcuODQ5NEM2My40NDY5IDcuNDY4NTQgNjMuMjM2NCA2Ljk0MjU5IDYzLjIzNjQgNi4yNzE1NUM2My4yMzY0IDUuNDY0NDkgNjMuNTY4NSA0Ljg0NjA1IDY0LjIzNDUgNC40MTI2QzY0LjkwMDUgMy45ODA5NiA2NS44Mjk3IDMuNzY1MTQgNjcuMDIzOSAzLjc2NTE0QzY4LjM0MzIgMy43NjUxNCA2OS4zNzIyIDQuMDI5OTIgNzAuMTEwOCA0LjU1NzY5QzcwLjg0OTUgNS4wODU0NSA3MS4yMTk3IDUuODUwNzkgNzEuMjE5NyA2Ljg1MDA5SDY4LjYyNjNDNjguNjI2MyA2LjAyMTI3IDY4LjA5ODIgNS42MDU5NiA2Ny4wNDAyIDUuNjA1OTZDNjYuNjY0NSA1LjYwNTk2IDY2LjM2ODcgNS42Njk0MyA2Ni4xNTI3IDUuNzkyNzZDNjUuOTM2OCA1LjkxNzkgNjUuODI3OSA2LjA4Mjk0IDY1LjgyNzkgNi4yODc4N0M2NS44Mjc5IDYuNjM5NzIgNjYuMTQgNi44OTU0MyA2Ni43NjYyIDcuMDU1MDNMNjguNzc4OCA3LjU1MDE1QzY5LjU2MjggNy43NDQyMSA3MC4xOTI1IDguMDQxNjQgNzAuNjY0MyA4LjQ0NjA4QzcxLjEzNjIgOC44NDg3IDcxLjM3MjEgOS40MTQ1NCA3MS4zNzIxIDEwLjE0MThDNzEuMzcyMSAxMC45NzI0IDcxLjA0IDExLjYwNTQgNzAuMzc0IDEyLjA0MjVDNjkuNzA3OSAxMi40Nzk2IDY4LjcyMjUgMTIuNjk5IDY3LjQxNCAxMi42OTlDNjUuOTU4NiAxMi42OTkgNjQuODU1MiAxMi40MTk3IDY0LjEwMzggMTEuODYyOUw2NC4xMDc1IDExLjg2NDdaIiBmaWxsPSJibGFjayIvPgo8cGF0aCBkPSJNNzIuODA2NiAwSDc1LjRWNy4yNjE3MUw3OC44MjgyIDMuOTM3MzZIODIuMDAwNEw3Ny43MTkzIDguMTE0MTFMODEuOTg0MSAxMi41MzAzSDc4LjgyODJMNzUuNCA4LjkxNTczVjEyLjUzMDNINzIuODA2NlYwWiIgZmlsbD0iYmxhY2siLz4KPC9zdmc+Cg==
      OPENPROJECT_SEED_DESIGN_MAIN__MENU__BG__COLOR: '#ffffff'
      OPENPROJECT_SEED_DESIGN_MAIN__MENU__BG__HOVER__BACKGROUND: '#f5f5f5'
      OPENPROJECT_SEED_DESIGN_MAIN__MENU__BG__SELECTED__BACKGROUND: '#571EFA'
      OPENPROJECT_SEED_DESIGN_PRIMARY__BUTTON__COLOR: '#571EFA'
      OPENPROJECT_SEED_LDAP_OPENDESK_ADMIN__MAPPING: opendeskProjectmanagementAdmin
      OPENPROJECT_SEED_LDAP_OPENDESK_BASEDN: dc=swp-ldap,dc=internal
      OPENPROJECT_SEED_LDAP_OPENDESK_BINDPASSWORD: 2de88f54e56405d78b0f6314eac4009a24939710
      OPENPROJECT_SEED_LDAP_OPENDESK_BINDUSER: uid=ldapsearch_openproject,cn=users,dc=swp-ldap,dc=internal
      OPENPROJECT_SEED_LDAP_OPENDESK_FILTER: (&(objectClass=opendeskProjectmanagementUser)(opendeskProjectmanagementEnabled=TRUE))
      OPENPROJECT_SEED_LDAP_OPENDESK_FIRSTNAME__MAPPING: givenName
      OPENPROJECT_SEED_LDAP_OPENDESK_GROUPFILTER_OPENDESK_BASE: dc=swp-ldap,dc=internal
      OPENPROJECT_SEED_LDAP_OPENDESK_GROUPFILTER_OPENDESK_FILTER: (&(objectClass=opendeskProjectmanagementGroup)(opendeskProjectmanagementEnabled=TRUE))
      OPENPROJECT_SEED_LDAP_OPENDESK_GROUPFILTER_OPENDESK_GROUP__ATTRIBUTE: cn
      OPENPROJECT_SEED_LDAP_OPENDESK_GROUPFILTER_OPENDESK_SYNC__USERS: "true"
      OPENPROJECT_SEED_LDAP_OPENDESK_HOST: ums-ldap-server
      OPENPROJECT_SEED_LDAP_OPENDESK_LASTNAME__MAPPING: sn
      OPENPROJECT_SEED_LDAP_OPENDESK_LOGIN__MAPPING: uid
      OPENPROJECT_SEED_LDAP_OPENDESK_MAIL__MAPPING: mailPrimaryAddress
      OPENPROJECT_SEED_LDAP_OPENDESK_PORT: "389"
      OPENPROJECT_SEED_LDAP_OPENDESK_SECURITY: plain_ldap
      OPENPROJECT_SEED_LDAP_OPENDESK_SYNC__USERS: "true"
      OPENPROJECT_SMTP__ADDRESS: postfix.default.svc.cluster.local
      OPENPROJECT_SMTP__AUTHENTICATION: cram_md5
      OPENPROJECT_SMTP__DOMAIN: opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      OPENPROJECT_SMTP__ENABLE__STARTTLS__AUTO: "true"
      OPENPROJECT_SMTP__OPENSSL__VERIFY__MODE: none
      OPENPROJECT_SMTP__PASSWORD: fe5f8ce805fbf2c067c4be175b34efd98ce64449
      OPENPROJECT_SMTP__PORT: 587
      OPENPROJECT_SMTP__SSL: "false"
      OPENPROJECT_SMTP__USER__NAME: opendesk-system@opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      OPENPROJECT_SOUVAP__NAVIGATION__SECRET: 3fcfc241e2b27da4baba1de8a3a75072ed4fca5f
      OPENPROJECT_SOUVAP__NAVIGATION__URL: https://portal.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com/univention/portal/navigation.json?base=https%3A//portal.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      OPENPROJECT_USER__DEFAULT__TIMEZONE: Europe/Berlin
    global:
      imagePullSecrets: []
    image:
      imagePullPolicy: IfNotPresent
      registry: registry.opencode.de
      repository: bmi/opendesk/components/supplier/openproject/images-mirror/open_desk
      tag: 16.1.1@sha256:2fe8a7d1cab42611b01f4ca20ce7179a0637477f2882364b4a1cfdebde9ecd6f
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 100M
        nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
        nginx.org/client-max-body-size: 100M
        nginx.org/proxy-read-timeout: 60s
        nginx.org/proxy-send-timeout: 60s
      enabled: true
      host: projects.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      ingressClassName: nginx
      tls:
        enabled: true
        secretName: opendesk-certificates-tls
    memcached:
      bundled: false
      connection:
        host: memcached
        port: 11211
    openproject:
      admin_user:
        locked: false
        mail: openproject-admin@swp-domain.internal
        name: OpenProject Internal Admin
        password: 0ed4915fb2a68510364593449c57b18c7ec82dc3
        password_reset: "false"
      host: projects.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      oidc:
        attribute_map:
          admin: openproject_admin
          login: opendesk_username
        authorizationEndpoint: /realms/opendesk/protocol/openid-connect/auth
        enabled: true
        endSessionEndpoint: https://id.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com/realms/opendesk/protocol/openid-connect/logout
        host: id.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
        identifier: opendesk-openproject
        provider: keycloak
        scope: '[openid,opendesk-openproject-scope]'
        secret: 4c280910f6cfb6c6e79a3d5a908bd6214cd3562a
        tokenEndpoint: /realms/opendesk/protocol/openid-connect/token
        userinfoEndpoint: /realms/opendesk/protocol/openid-connect/userinfo
      seed_locale: de
      tmpVolumesAnnotations: null
      useTmpVolumes: true
    persistence:
      enabled: false
    podAnnotations: null
    postgresql:
      auth:
        database: openproject
        password: 2f8fea4e3716ce8fa44ae96bd699ea77347519f9
        username: openproject_user
      bundled: false
      connection:
        host: postgresql
        port: 5432
    probes:
      liveness:
        failureThreshold: 30
        initialDelaySeconds: 300
      readiness:
        failureThreshold: 30
        initialDelaySeconds: 150
    replicaCount: 1
    resources:
      limits:
        cpu: 99
        memory: 2Gi
      requests:
        cpu: 0.1
        memory: 768Mi
    s3:
      auth:
        accessKeyId: openproject_user
        secretAccessKey: fcfa935cf477f5c2941df0447257d1ae1895a37f
      bucketName: openproject
      directUploads: true
      enableSignatureV4Streaming: true
      enabled: true
      endpoint: https://objectstore.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      host: https://objectstore.opendeskk8s.blueprints.shoot.canary.k8s-hana.ondemand.com
      pathStyle: true
      region: eu-west-1
      useIamProfile: false
    seederJob:
      annotations:
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
        intents.otterize.com/service-name: openproject-seeder
      resources:
        limits:
          cpu: 99
          memory: 768Mi
        requests:
          cpu: 0.1
          memory: 256Mi
    serviceAccount:
      annotations: null
    workers:
      default:
        resources:
          limits:
            cpu: 99
            memory: 4Gi
          requests:
            cpu: 0.25
            memory: 512Mi
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: openproject-openproject-config-map
