apiVersion: v1
data:
  values.yaml: |
    cleanup:
      deletePodsOnSuccess: true
      deletePodsOnSuccessTimeout: 60
    commonAnnotations: null
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      enabled: true
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
      seLinuxOptions: null
      seccompProfile:
        type: RuntimeDefault
    global:
      imagePullSecrets: []
    image:
      imagePullPolicy: IfNotPresent
      registry: registry-1.docker.io
      repository: library/mariadb
      tag: 10.6.21@sha256:8a16204dc96c08ed0ee2c52c0f9324aa5d2dd0e43ad23a471d447a39f75765b5
    job:
      databases:
        - name: openxchange_dummy
          user: openxchange_user
      enabled: true
      retries: 10
      users:
        - connectionLimit: 100
          password: 7d2a168ba0332d660a93b2498e3ed3accfe78565
          username: openxchange_user
      wait: 30
    mariadb:
      rootPassword:
        value: 0de728d884563ec90fc9c02fae257f0cfe647bc9
    persistence:
      annotations: null
      size: 1Gi
      storageClass: null
    podAnnotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
    replicaCount: 1
    resources:
      limits:
        cpu: 99
        memory: 2Gi
      requests:
        cpu: 0.1
        memory: 384Mi
    service:
      annotations: null
    serviceAccount:
      annotations: null
kind: ConfigMap
metadata:
  name: services-external-mariadb-config-map
