---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: poc-opendesk
  path: "./flux"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: poc-opendesk
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: poc-opendesk
  path: "./ocm-k8s-toolkit"
  prune: true
  timeout: 1m