name: "ðŸ“¦ OCM: Package, Release & Transfer"

run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
    && format('Manual release: {0}', inputs.version)
    || format('Automatic release') }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to set/publish the OCM packages as. E.g., "1.2.3". If not provided, the version will be auto-incremented based on the latest existing tag.'
        required: false
        type: string
  push:
    branches:
      - main
    paths:
      - "**/helmfile/**"
      - "**/component-constructor.yaml"

permissions:
  pull-requests: write
  contents: write
  packages: write
  actions: write
  checks: write
  statuses: write

jobs:
  bump-version:
    name: Get OCM Version
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/re-get-version.yml
    with:
      bumped: true
      version: ${{ github.event.inputs.version || '' }}
  publish-configmaps:
    name: Publish ConfigMaps
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    needs:
      - bump-version
    uses: ./.github/workflows/re-publish-configmaps.yml
    with:
      version: ${{ needs.bump-version.outputs.version }}
      oci_registry: ghcr.io
      oci_repository: ${{ github.repository }}
    secrets:
      oci_reg_username: ${{ github.actor }}
      oci_reg_password: ${{ secrets.GITHUB_TOKEN }}
  find-constructors:
    name: Find Component Constructors
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/re-find-constructors.yml
  publish-ocm:
    name: Publish OCM Packages
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    needs:
      - bump-version
      - publish-configmaps
      - find-constructors
    uses: ./.github/workflows/re-publish-ocm.yaml
    with:
      files: ${{ needs.find-constructors.outputs.files }}
      dry-run: false
      version: ${{ needs.bump-version.outputs.version }}
      oci_registry: ghcr.io
      oci_repository: ${{ github.repository }}
    secrets:
      oci_reg_username: ${{ github.actor }}
      oci_reg_password: ${{ secrets.GITHUB_TOKEN }}
  create-release:
    name: Create GitHub Release
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: [ubuntu-latest]
    needs:
      - bump-version
      - publish-ocm
    steps:
      - uses: actions/checkout@v6
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ocm-${{ needs.bump-version.outputs.version }}
          name: Release ${{ needs.bump-version.outputs.version }}
          generateReleaseNotes: true
