name: Build ConfigMaps

on:
  workflow_call: {}

jobs:
  helmfiles-build:
    name: Helmfiles Build
    runs-on: [solinas]
    steps:
      - uses: actions/checkout@v5
        name: Checkout
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v2.1.0

      - name: build-configmaps
        shell: bash
        run: |
          set -euo pipefail
          ############################################################
          make all
          make clean

      - name: Commit files
        shell: bash
        run: |
          set -euo pipefail
          ############################################################
          git add ocm/values-config-maps/
          if ! git diff --cached --quiet; then
            git commit -m "chore: update generated helmfiles and configmaps"
            git push
          else
            echo "No changes to commit"
          fi
