name: Publish ConfigMaps

on:
  workflow_call: 
    inputs:
      version:
        description: 'The version to publish the ConfigMaps as'
        required: true
        type: string
      oci_registry:
        description: 'The OCI registry to publish the ConfigMaps to'
        required: false
        type: string
        default: 'ghcr.io'
    secrets:
      oci_reg_username:
        description: 'The username for the OCI registry'
        required: true
      oci_reg_password:
        description: 'The password for the OCI registry'
        required: true

jobs:
  values-configmap:
    runs-on: [solinas]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'v2.6.4'

      - name: Login to OCI Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.oci_registry }}
          username: ${{ secrets.oci_reg_username }}
          password: ${{ secrets.oci_reg_password }}

      - name: Push ConfigMap manifests
        run: |
          flux push artifact oci://ghcr.io/opendesk-ocm-k8s-toolkit-values-configmaps:${{ inputs.version }} \
            --path="./ocm/values-config-maps" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)"